import os
HERE=os.path.dirname(os.path.realpath(__file__)); OUT=os.path.join(HERE,'.out'); os.makedirs(OUT, exist_ok=True)
__file__=os.path.join(HERE,'test_ranch.py')
exec(open(__file__).read().split('with sync_playwright() as pw:')[0].replace('PORT=8765','PORT=8783'))
# the page in real step mode (automated browsers otherwise see every step at once)
POLY="{type:'Polygon',coordinates:[[[-100.458,35.515],[-100.42183,35.515],[-100.42183,35.54446],[-100.458,35.54446],[-100.458,35.515]]]}"
def vis(pg, s): return pg.is_visible('#step_' + s)
with sync_playwright() as pw:
    b=pw.chromium.launch(); errs=[]
    for W,H,tag in [(1360,1000,'desk'),(390,844,'phone')]:
        c=b.new_context(viewport={'width':W,'height':H}); c.route('**/*', route); c.add_init_script("window.__MR_STEPS=1")
        pg=c.new_page(); pg.on('pageerror', lambda e: errs.append(str(e)))
        pg.goto(f'http://127.0.0.1:{PORT}/my-ranch/index.html'); pg.wait_for_timeout(700)
        check(tag+': new ranch opens on step 1 only', vis(pg,'ranch') and not vis(pg,'herd') and not vis(pg,'plan') and not vis(pg,'decide'))
        check(tag+': strip asks to draw', 'draw your pastures' in pg.inner_text('#mrStrip').lower())
        pg.evaluate("MyRanch.addPasture(%s,{name:'Range',type:'range',mode:'manual',manual:3200})" % POLY); pg.wait_for_timeout(400)
        pg.click('.mr-next [data-go="herd"]' if W>500 else '.mr-step-btn[data-go="herd"]'); pg.wait_for_timeout(300)
        check(tag+': next goes to herd', vis(pg,'herd') and not vis(pg,'ranch') and pg.evaluate("MyRanch.step()")=='herd')
        check(tag+': ranch step ticked', 'done' in pg.get_attribute('.mr-step-btn[data-go="ranch"]','class'))
        pg.fill('#hd_cows','154'); pg.wait_for_timeout(900)
        pg.click('.mr-step-btn[data-go="plan"]'); pg.wait_for_timeout(600)
        check(tag+': plan shows headline and 4 tiles', vis(pg,'plan') and len(pg.inner_text('#fc_headline'))>40 and pg.locator('#fc_tiles .stat-tile').count()==4, pg.inner_text('#fc_headline')[:120])
        check(tag+': chart drawn with width after showing the step', pg.evaluate("document.querySelector('#fc_chart svg') && document.querySelector('#fc_chart svg').getBoundingClientRect().width > 250"))
        st=pg.inner_text('#mrStrip')
        check(tag+': strip filled', '%' in st and '$' in st and ' ac' in st, st)
        check(tag+': details closed by default', pg.evaluate("[...document.querySelectorAll('#step_plan details')].every(d=>!d.open)"))
        pg.click('.mr-step-btn[data-go="decide"]'); pg.wait_for_timeout(1200)
        check(tag+': decisions drawn', vis(pg,'decide') and pg.locator('#dec_calvChart .pc-bar').count()==12)
        pg.click('#stripSaveBtn'); pg.wait_for_timeout(200)
        check(tag+': save button opens file panel', pg.is_visible('#exportGeoBtn')); pg.click('#stripSaveBtn'); pg.wait_for_timeout(100)
        check(tag+': save button closes it', not pg.is_visible('#exportGeoBtn'))
        pg.click('.mr-step-btn[data-go="ranch"]'); pg.wait_for_timeout(300)
        check(tag+': map sized when back on step 1', pg.evaluate("document.getElementById('map').getBoundingClientRect().width > 200"))
        pg.click('.mr-step-btn[data-go="plan"]'); pg.wait_for_timeout(200)
        pg.reload(); pg.wait_for_timeout(900)
        check(tag+': reopens on the last step', vis(pg,'plan') and not vis(pg,'ranch'))
        check(tag+': no horizontal scroll', pg.evaluate("document.documentElement.scrollWidth <= innerWidth + 1"), pg.evaluate("document.documentElement.scrollWidth"))
        pg.screenshot(path=os.path.join(OUT,'steps_%s.png' % tag), full_page=True)
        c.close()
    check('no JS errors', not errs, errs)
    b.close()
print('\n%d failures' % len(fails)); sys.exit(1 if fails else 0)
