import os
HERE=os.path.dirname(os.path.realpath(__file__)); OUT=os.path.join(HERE,'.out'); os.makedirs(OUT, exist_ok=True)
__file__=os.path.join(HERE,'test_ranch.py')
exec(open(__file__).read().split('with sync_playwright() as pw:')[0].replace('PORT=8765','PORT=8777'))
import json
with sync_playwright() as pw:
    b=pw.chromium.launch(); ctx=b.new_context(viewport={'width':1360,'height':1300}); ctx.route('**/*', route); pg=ctx.new_page()
    errs=[]; pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto(f'http://127.0.0.1:{PORT}/my-ranch/index.html'); pg.wait_for_timeout(600)
    # build a ranch and export it
    pg.fill('#ranchName','Export ranch'); pg.dispatch_event('#ranchName','input')
    pg.evaluate("MyRanch.addPasture({type:'Polygon',coordinates:[[[-100.4,35.5],[-100.37,35.5],[-100.37,35.52],[-100.4,35.52],[-100.4,35.5]]]},{name:'Range',type:'range',mode:'manual',manual:2600})")
    pg.evaluate("Object.assign(MyRanch.state().herd,{cowLb:1100,start1:'04-01',calving:'one',len1:63,weanLb:426})")
    pg.fill('#hd_cows','154'); pg.wait_for_timeout(800)
    f=os.path.join(OUT,'export.geojson'); json.dump(pg.evaluate("MyRanch.toGeoJSON()"), open(f,'w'))
    sup=pg.evaluate("MyRanch.feed().totals.sup")
    # another device with its own ranch
    c2=b.new_context(); c2.route('**/*', route); p2=c2.new_page(); p2.on('pageerror', lambda e: errs.append(str(e)))
    p2.goto(f'http://127.0.0.1:{PORT}/my-ranch/index.html'); p2.wait_for_timeout(600)
    p2.evaluate("MyRanch.addPasture({type:'Polygon',coordinates:[[[-99.3,33.1],[-99.29,33.1],[-99.29,33.11],[-99.3,33.11],[-99.3,33.1]]]},{name:'Old',type:'improved',mode:'manual',manual:3000})")
    p2.fill('#hd_cows','40'); p2.wait_for_timeout(400)
    p2.once('dialog', lambda d: d.dismiss())
    p2.set_input_files('#fileInput', f); p2.wait_for_timeout(1500)
    st=p2.evaluate("MyRanch.state()")
    check('cancel keeps own ranch and adds pastures only', len(st['pastures'])==2 and st['herd']['cows']==40)
    p2.once('dialog', lambda d: d.accept())
    p2.set_input_files('#fileInput', f); p2.wait_for_timeout(1500)
    st=p2.evaluate("MyRanch.state()")
    check('replace loads whole ranch', [p['name'] for p in st['pastures']]==['Range'] and p2.input_value('#hd_cows')=='154' and p2.input_value('#ranchName')=='Export ranch' and p2.input_value('#hd_cowLb')=='1100', [p['name'] for p in st['pastures']])
    check('old map shapes removed', p2.locator('path.leaflet-interactive').count()==1)
    check('same results after import', abs(p2.evaluate("MyRanch.feed().totals.sup")-sup)<1e-6)
    check('notice says loaded', 'Loaded' in p2.inner_text('#fileNotice'))
    p2.reload(); p2.wait_for_timeout(700)
    check('persists after reload', p2.evaluate("MyRanch.state().herd.cows")==154)
    c3=b.new_context(); c3.route('**/*', route); p3=c3.new_page(); dlg=[]; p3.on('dialog', lambda d: (dlg.append(1), d.accept()))
    p3.goto(f'http://127.0.0.1:{PORT}/my-ranch/index.html'); p3.wait_for_timeout(600)
    p3.set_input_files('#fileInput', f); p3.wait_for_timeout(1500)
    check('empty device loads without asking', not dlg and p3.evaluate("MyRanch.state().herd.cows")==154)
    check('no JS errors', not errs, errs)
    b.close()
print('\n%d failures' % len(fails)); sys.exit(1 if fails else 0)
