import os
HERE=os.path.dirname(os.path.abspath(__file__)); REPO=os.path.abspath(os.path.join(HERE,'..','..')); OUT=os.path.join(HERE,'.out'); os.makedirs(OUT, exist_ok=True)
exec(open(os.path.join(HERE,'test_ranch.py')).read().split("with sync_playwright() as pw:")[0])
with sync_playwright() as pw:
    b=pw.chromium.launch(); ctx=b.new_context(viewport={'width':1280,'height':900}); ctx.route('**/*', route); pg=ctx.new_page()
    errs=[]; pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto(f'http://127.0.0.1:{PORT}/index.html'); pg.wait_for_timeout(400)
    check('preview hidden with no ranch', not pg.is_visible('#myRanchPreview'))
    pg.goto(f'http://127.0.0.1:{PORT}/my-ranch/index.html'); pg.wait_for_timeout(500)
    pg.fill('#ranchName','North place')
    pg.evaluate("MyRanch.addPasture({type:'Polygon',coordinates:[[[-99.3,33.1],[-99.29,33.1],[-99.29,33.11],[-99.3,33.11],[-99.3,33.1]]]},{name:'T'})"); pg.wait_for_timeout(800)
    pg.goto(f'http://127.0.0.1:{PORT}/index.html'); pg.wait_for_timeout(400)
    t=pg.inner_text('#myRanchPreview') if pg.is_visible('#myRanchPreview') else ''
    check('preview shows saved ranch', 'North place' in t and '256 acres' in t, t)
    check('BCU calculator still computes', '$673.26' in pg.inner_text('#bcuHeaderValue'))
    check('no My Ranch feed box before sending', not pg.is_visible('#bcuRanch'))
    pg.evaluate("localStorage.setItem('tamuDecisionAidsRanchFeed', JSON.stringify({hay:100,supplement:20,feeding:10,total:130,ranch:'North place',cows:90}))")
    pg.reload(); pg.wait_for_timeout(400)
    pg.evaluate("document.getElementById('bcuToggleBtn').click()"); pg.wait_for_timeout(200)
    check('My Ranch feed offered in BCU', pg.is_visible('#bcuRanch') and '$130.00' in pg.inner_text('#bcuRanchText'))
    pg.check('#bcu_useRanchFeed'); pg.wait_for_timeout(200)
    # default BCU: hay 1.5*105=157.5 + protein 1.5*1000*0.2/100*20=60 -> replaced by 130
    v=float(pg.inner_text('#bcuHeaderValue').replace('$','').replace(',',''))
    check('BCU uses My Ranch feed', abs(v-(673.26-157.5-60+130))<0.02, v)
    pg.reload(); pg.wait_for_timeout(300)
    check('choice persists', pg.is_checked('#bcu_useRanchFeed') and abs(float(pg.inner_text('#bcuHeaderValue').replace('$','').replace(',',''))-v)<0.01)
    pg.evaluate("document.getElementById('bcuToggleBtn').click()"); pg.wait_for_timeout(100); pg.click('#bcu_resetBtn'); pg.wait_for_timeout(200)
    check('reset returns to default', '$673.26' in pg.inner_text('#bcuHeaderValue') and not pg.is_checked('#bcu_useRanchFeed'))
    pg.screenshot(path=os.path.join(OUT,'portal.png'))
    pg.click('#my-ranch-link a'); pg.wait_for_timeout(400)
    check('card links to My Ranch', pg.url.endswith('/my-ranch/index.html'))
    check('no JS errors', not errs, errs)
    b.close()
print(len(fails),'failures')
