import os
HERE=os.path.dirname(os.path.abspath(__file__)); REPO=os.path.abspath(os.path.join(HERE,'..','..')); OUT=os.path.join(HERE,'.out'); os.makedirs(OUT, exist_ok=True)
exec(open(os.path.join(HERE,'test_ranch.py')).read().split('with sync_playwright() as pw:')[0].replace('PORT=8765','PORT=8767'))
def sq(x0,y0,d=0.02): return {'type':'Polygon','coordinates':[[[x0,y0],[x0+d,y0],[x0+d,y0+d],[x0,y0+d],[x0,y0]]]}
with sync_playwright() as pw:
    b=pw.chromium.launch(); ctx=b.new_context(viewport={'width':1360,'height':1000}); ctx.route('**/*', route)
    ctx.add_init_script("window.MR_TODAY='2026-10-02';")
    pg=ctx.new_page(); errs=[]; pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto(f'http://127.0.0.1:{PORT}/my-ranch/index.html'); pg.wait_for_timeout(700)
    for i,n in enumerate(['North','Middle','South']):
        pg.evaluate(f"MyRanch.addPasture({json.dumps(sq(-99.3+i*0.021,33.1))},{{name:'{n}',type:'improved',mode:'manual',manual:{3000+i*500}}})")
    pg.fill('#hd_cows','80') if pg.locator('#hd_cows').count() else None
    pg.evaluate("MyRanch.state().herd.cows=80"); pg.evaluate("MyRanch.importObject({})") if False else None
    pg.locator('input[id*="cows"]').first.fill('80'); pg.locator('input[id*="cows"]').first.dispatch_event('input'); pg.wait_for_timeout(500)
    t=pg.evaluate("(function(){var t=MyRanch.grassToday(); return {n:t.list.length, here:t.list.filter(r=>r.herdHere).length, herd:t.herd&&t.herd.p.name, src:t.herd&&t.herd.source, days:t.list.map(r=>r.days)}})()")
    check('grass today: one row per pasture', t['n']==3, t)
    check('calendar puts herd in exactly one pasture', t['here']==1 and t['src']=='plan', t)
    check('days of grass are numbers >= 0', all(d>=0 for d in t['days']), t['days'])
    check('herd-now section shown', pg.locator('#hn_pid').count()==1 and 'By the grazing calendar' in pg.inner_text('#hn_msg'), pg.inner_text('#hn_msg'))
    check('map starts in pasture colors', not pg.is_visible('#grassLegend'))
    pg.click('[data-mapcolor="grass"]'); pg.wait_for_timeout(300)
    check('grass legend shows', pg.is_visible('#grassLegend') and '3+ weeks' in pg.inner_text('#grassLegend'))
    labels=pg.evaluate("Array.from(document.querySelectorAll('.pasture-label')).map(e=>e.textContent)")
    check('map labels show grass days and herd', any('🐄' in l for l in labels) and sum('d grass' in l for l in labels)==2, labels)
    check('herd marker on map', pg.locator('.herd-icon').count()==1)
    fills=pg.evaluate("Array.from(document.querySelectorAll('path.leaflet-interactive')).map(p=>p.getAttribute('fill'))")
    check('herd pasture painted crimson', '#8B0215' in fills, fills)
    # actual location
    mid=pg.evaluate("MyRanch.state().pastures[1].id")
    pg.select_option('#hn_pid', mid); pg.wait_for_timeout(300)
    check('since date defaults to today', pg.input_value('#hn_since')=='2026-10-02')
    pg.fill('#hn_since','2026-09-27'); pg.dispatch_event('#hn_since','change'); pg.wait_for_timeout(300)
    h=pg.evaluate("(function(){var h=MyRanch.grassToday().herd; return {n:h.p.name, din:h.daysIn, stay:h.stay, left:h.left, mb:h.moveBy.toISOString().slice(0,10), next:h.next&&h.next.p.name, ac:h.acPerAU}})()")
    check('herd in Middle 5 days', h['n']=='Middle' and h['din']==5, h)
    check('days left = stay - days in', h['left']==max(0,h['stay']-5), h)
    import datetime as dt
    check('move-by date = since + stay', h['mb']==(dt.date(2026,9,27)+dt.timedelta(days=h['stay'])).isoformat(), h)
    check('message names pasture, date and next', 'Middle' in pg.inner_text('#hn_msg') and 'Sep 27' in pg.inner_text('#hn_msg'), pg.inner_text('#hn_msg'))
    check('ac per AU while there', h['ac'] and h['ac']>0)
    labels=pg.evaluate("Array.from(document.querySelectorAll('.pasture-label')).map(e=>e.textContent)")
    check('map follows your herd location', any(l.startswith('🐄 Middle') for l in labels), labels)
    check('max stay respected', h['stay']<=30)
    # more cows -> fewer days of grass
    d1=pg.evaluate("MyRanch.grassToday().list.map(r=>r.days).reduce((a,b)=>a+b,0)")
    pg.locator('input[id*="cows"]').first.fill('160'); pg.locator('input[id*="cows"]').first.dispatch_event('input'); pg.wait_for_timeout(500)
    d2=pg.evaluate("MyRanch.grassToday().list.map(r=>r.days).reduce((a,b)=>a+b,0)")
    check('doubling the herd cuts days of grass', d2<d1*0.75, (d1,d2))
    pg.fill('#hn_since','2026-10-20'); pg.dispatch_event('#hn_since','change'); pg.wait_for_timeout(300)
    check('future date warned', 'future' in pg.inner_text('#hn_msg').lower(), (pg.inner_text('#hn_msg'), pg.evaluate('JSON.stringify(MyRanch.state().herdNow)')))
    pg.fill('#hn_since','2026-09-27'); pg.dispatch_event('#hn_since','change'); pg.wait_for_timeout(200)
    pg.evaluate("MyRanch.fit()"); pg.wait_for_timeout(300); pg.locator('.map-card').screenshot(path=os.path.join(OUT,'grass-map.png'))
    pg.locator('#herdNow').screenshot(path=os.path.join(OUT,'grass-table.png'))
    pg.reload(); pg.wait_for_timeout(800)
    check('mode and herd location persist', pg.is_visible('#grassLegend') and pg.evaluate("MyRanch.state().herdNow.pid")==mid)
    pg.select_option('#hn_pid',''); pg.wait_for_timeout(200)
    check('back to calendar', pg.evaluate("MyRanch.state().herdNow")==None and 'By the grazing calendar' in pg.inner_text('#hn_msg'))
    pg.click('[data-mapcolor="name"]'); pg.wait_for_timeout(200)
    check('pastures mode restores names', not pg.is_visible('#grassLegend') and pg.locator('.herd-icon').count()==0 and any(' ac' in l for l in pg.evaluate("Array.from(document.querySelectorAll('.pasture-label')).map(e=>e.textContent)")))
    m=ctx.new_page(); m.set_viewport_size({'width':390,'height':844}); m.goto(f'http://127.0.0.1:{PORT}/my-ranch/index.html'); m.wait_for_timeout(800)
    m.click('[data-mapcolor="grass"]'); m.wait_for_timeout(300)
    check('phone: no horizontal scroll', m.evaluate('document.documentElement.scrollWidth')<=390, m.evaluate('document.documentElement.scrollWidth'))
    m.locator('#map').screenshot(path=os.path.join(OUT,'grass-mobile.png'))
    check('no JS errors', not errs, errs)
    b.close()
print('\n%d failures' % len(fails)); sys.exit(1 if fails else 0)
